displayName: WebSocket Connection Balancer
type: middleware

import: github.com/K8Trust/traefikwsbalancer

summary: 'A Traefik middleware plugin that balances WebSocket connections across multiple pods based on connection count'

testData:
  metricPath: /metric
  pods:
    - http://test-pod-1:8080
    - http://test-pod-2:8080
  tlsVerify: true
  cacheTTL: 30s
  dialTimeout: 10s
  writeTimeout: 10s
  readTimeout: 30s