# .traefik.yml
displayName: WebSocket Connection Balancer
type: middleware
import: github.com/K8Trust/traefikwsbalancer
summary: Balance WebSocket connections across multiple backends based on connection count

testData:
  metricPath: /metric
  balancerMetricPath: /balancer-metrics
  services:
    - http://websocket-service-1.default.svc.cluster.local:80
  cacheTTL: 30
  enableIPScanning: true
  discoveryTimeout: 5