# .traefik.yml
displayName: WebSocket Connection Balancer
type: middleware
import: github.com/K8Trust/traefikwsbalancer
summary: Balance WebSocket connections across multiple backends based on connection count
iconPath: /assets/icon.png

testData:
  metricPath: /metric
  pods:
    - http://localhost:8081
    - http://localhost:8082
  cacheTTL: 30