# .traefik.yml
displayName: WebSocket Connection Balancer
type: middleware
import: github.com/K8Trust/traefikwsbalancer
summary: Balance WebSocket connections across multiple backends based on connection count

testData:
  metricPath: /metric
  services:
    - http://websocket-service-1.default.svc.cluster.local:80
    - http://websocket-service-2.default.svc.cluster.local:80
  cacheTTL: 30